default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails
  password: password

development:
  database: malicious_time_development
  <<: *default

test:
  <<: *default
  database: malicious_time_test

production:
  <<: *default
  database: malicious_time_production
